version: 2
updates:
  # 1. Memantau dependensi PHP (Composer)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7 # Menunda PR untuk versi baru selama 7 hari

  # 2. Memantau GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7 # Wajib menggunakan default-days karena Actions tidak menggunakan semver murni
